[package]
name = "rust-crud-api"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version = "0.8", features = ["multipart"] }
tokio = { version = "1.40", features = ["full", "process"] }
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }